name: iOS

on: [push, pull_request]

jobs:
  some-job:
    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
    - name: Checkout project
      uses: actions/checkout@v1

    - name: Specify node version
      uses: actions/setup-node@v1
      with:
        node-version: 16

    - name: Install node_modules & deploy with specific XCode version
      run: |
        yarn install --frozen-lockfile
        yarn pods
        
    - name: iOS test
      timeout-minutes: 10
      run: |
        yarn test
